pointcloud_slice_to_scan:
  ros__parameters:
    input_cloud_topic: "/livox/lidar"
    output_scan_topic: "/scan_knee"

    # ---------------------------------------------------------
    # Horizontal slice limits in the LiDAR frame
    # Keep only points with:
    #   slice_z_min <= z <= slice_z_max
    #
    # IMPORTANT:
    # These are relative to the MID360 frame.
    # You will manually tune these depending on where the LiDAR is mounted.
    #
    # Example:
    #   If LiDAR is mounted above the knee level, knee slice may be negative z.
    #   If LiDAR is mounted below or close to knee level, values will differ.
    # ---------------------------------------------------------
    slice_z_min: -0.60
    slice_z_max: -0.05

    # Full 360 degree scan
    angle_min: -3.141592653589793
    angle_max: 3.141592653589793

    # Angular resolution of the output scan
    num_beams: 720

    # Distance limits in meters
    range_min: 0.05
    range_max: 10.0

    # Metadata only
    scan_time: 0.10

    # Fill empty bins with inf
    use_inf: true

    # Log stats every 20 clouds
    verbose: true